### ISSUE TITLE
Albedo map not provided while using model like InstantMesh

### ISSUE THREAD

**Issue by JINNMnm** [Aleafy/Make_it_Real#10]
Thanks for your amazing work!
I’m wondering if a model like InstantMesh can generate both a mesh and texture without a provided albedo map. In this case, I want to use the model to obtain the PBR material for the mesh. Does it only support inputs that include an albedo map?

**Comment by SunzeY** [comment]
Yes, we only support input with albedo map. Our pipeline is the next step that synthesize other PBR maps based on albedo-only map.

**Comment by JINNMnm** [comment]
Thank you for your response, I'll close this issue now.
