### ISSUE TITLE
Dependency issues during installation: unsatisfiable scipy version

### ISSUE THREAD

**Issue by WilliamHaiweiGu** [Aleafy/Make_it_Real#3]
Hello! First of all, thank you for open-sourcing your amazing work.

I encountered some dependency issues following the instructions in the `INSTALL.md` file.

The logging information shows that: `semantic-sam 1.0 requires scikit-image==0.21.0`, `scikit-image 0.21.0 requires scipy>=1.8`, and `kaolin 0.11.0 requires scipy<=1.5.2,>=1.2.0`. The dependencies cannot be resolved because no version of `scipy` can satisfy all 3.

Please resolve this issue. Thank you very much!

P.S. How to reproduce:

Follow  `INSTALL.md`, after executing `pip install git+https://github.com/UX-Decoder/Semantic-SAM.git@package`, an error message is shown:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
kaolin 0.11.0 requires scipy<=1.5.2,>=1.2.0, but you have scipy 1.10.1 which is incompatible.
```
Execute `pip uninstall scipy && pip install scipy==1.5.2`, an error message is shown:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scikit-image 0.21.0 requires scipy>=1.8, but you have scipy 1.5.2 which is incompatible.
```
Execute `pip uninstall scikit-image && pip install scikit-image==0.18.3`, an error message is shown:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
semantic-sam 1.0 requires scikit-image==0.21.0, but you have scikit-image 0.18.3 which is incompatible.
```

**Comment by Aleafy** [comment]
@WilliamHaiweiGu

Hi there,

Thank you for your interest in our project and for bringing this issue to our attention.

I have updated the [INSTALL.md](https://github.com/Aleafy/Make_it_Real/blob/main/INSTALL.md) to address the installation issue. The compatibility problem with the dependencies should not affect the subsequent operation of the project. You have two options:

1. You can choose to keep your current environment as it is.
2. Alternatively, you can reinstall `kaolin` 0.13.0 using the following command to avoid the error:

   ```sh
   pip install kaolin==0.13.0 -f https://nvidia-kaolin.s3.us-east-2.amazonaws.com/torch-1.10.1_cu111.html

**Comment by WilliamHaiweiGu** [comment]
Problem solved.
