### ISSUE TITLE
Installation issue: file som/ckpts/download_ckpt.sh does not exist

### ISSUE THREAD

**Issue by WilliamHaiweiGu** [Aleafy/Make_it_Real#4]
Hello, I encountered another issue during installation.

After following [INSTALL.md](https://github.com/Aleafy/Make_it_Real/blob/main/INSTALL.md), I was still unable to "get model weight through `bash som/ckpts/download_ckpt.sh`" because that file does not exist.

Directory `som/ckpts` is not present either. It appears that `som/ckpts` was put in [.gitignore](https://github.com/Aleafy/Make_it_Real/blob/main/.gitignore).

**Comment by Aleafy** [comment]
Hello,

It looks like the `som/ckpts` directory was gitignored. I have now added the missing file. You can also download it now using the command or from official Semantic-SAM [Github repo](https://github.com/UX-Decoder/Semantic-SAM).

If you encounter any further issues, feel free to reach out. We will also be adding more tests to this version to prevent similar issues in the future.
